services:
  backend:
    build: ./demo
    container_name: complaint-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
    restart: unless-stopped

  frontend:
    build: ./complaint-management-frontend
    container_name: complaint-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped