services:
  mysql:
    image: mysql:8.0
    container_name: complaint-mysql-simple
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: complaint_db
      MYSQL_USER: complaint_user
      MYSQL_PASSWORD: complaint_pass
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./demo
    container_name: complaint-backend-simple
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/complaint_db
      - SPRING_DATASOURCE_USERNAME=complaint_user
      - SPRING_DATASOURCE_PASSWORD=complaint_pass
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build: ./complaint-management-frontend
    container_name: complaint-frontend-simple
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: unless-stopped