all:
  children:
    ec2_instances:
      hosts:
        cms-server:
          ansible_host: 13.53.127.7  # Replace with actual EC2 IP
          ansible_user: ec2-user
          ansible_ssh_private_key_file: "./riyaz-pass.pem"
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        ansible_python_interpreter: /usr/bin/python3