---
- name: Deploy Complaint Management System
  hosts: production
  become: yes
  vars:
    app_name: complaint-management-system
    app_user: ec2-user
    app_dir: /home/ec2-user/Complaint_Management_System
    
  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest
        
    - name: Install required packages
      yum:
        name:
          - git
          - docker
        state: present
        
    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: Add user to docker group
      user:
        name: "{{ app_user }}"
        groups: docker
        append: yes
        
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        
    - name: Clone or update application repository
      git:
        repo: https://github.com/RayzJ/Complaint_Management_System.git
        dest: "{{ app_dir }}"
        force: yes
      become_user: "{{ app_user }}"
      
    - name: Stop existing containers
      shell: docker-compose down
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes
      become_user: "{{ app_user }}"
      
    - name: Build and start application
      shell: docker-compose up -d --build
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}"
      
    - name: Wait for application to start
      wait_for:
        port: 80
        host: localhost
        delay: 30
        timeout: 300
        
    - name: Verify application health
      uri:
        url: http://localhost:80
        method: GET
        status_code: 200
      retries: 5
      delay: 10