---
- name: Provision EC2 Instance for Complaint Management System
  hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    instance_type: t2.micro
    ami_id: ami-0c02fb55956c7d316  # Ubuntu 20.04 LTS
    key_name: your-key-pair
    security_group: complaint-sg
    
  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group }}"
        description: Security group for Complaint Management System
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 8080
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow SSH, HTTP, and Spring Boot
        tags:
          Name: "{{ security_group }}"
          
    - name: Launch EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: true
        region: "{{ region }}"
        count: 1
        instance_tags:
          Name: complaint-management-server
          Environment: production
        assign_public_ip: yes
      register: ec2_instance
      
    - name: Display instance information
      debug:
        msg: "Instance {{ ec2_instance.instances[0].id }} launched with IP {{ ec2_instance.instances[0].public_ip }}"